package http

const (
	HeaderAccept         = "Accept"
	HeaderCharset        = "Accept-Charset"
	HeaderAcceptEncoding = "Accept-Encoding"
	HeaderAcceptLanguage = "Accept-Language"
	HeaderAcceptPatch    = "Accept-Patch"
	HeaderAcceptRanges   = "Accept-Ranges"

	HeaderAccessControlAllowCredentials = "Access-Control-Allow-Credentials"
	HeaderAccessControlAllowHeaders     = "Access-Control-Allow-Headers"
	HeaderAccessControlAllowMethods     = "Access-Control-Allow-Methods"
	HeaderAccessControlAllowOrigin      = "Access-Control-Allow-Origin"
	HeaderAccessControlExposeHeaders    = "Access-Control-Expose-Headers"
	HeaderAccessControlMaxAge           = "Access-Control-Max-Age"
	HeaderAccessControlRequestHeaders   = "Access-Control-Request-Headers"
	HeaderAccessControlRequestMethod    = "Access-Control-Request-Method"

	HeaderAge                = "Age"
	HeaderAllow              = "Allow"
	HeaderAuthorization      = "Authorization"
	HeaderCacheControl       = "Cache-Control"
	HeaderConnection         = "Connection"
	HeaderContentDisposition = "Content-Disposition"
	HeaderContentEncoding    = "Content-Encoding"
	HeaderContentLanguage    = "Content-Language"
	HeaderContentLength      = "Content-Length"
	HeaderContentType        = "Content-Type"
	HeaderCookie             = "Cookie"
	HeaderDate               = "Date"
	HeaderETag               = "ETag"
	HeaderExpect             = "Expect"
	HeaderExpires            = "Expires"
	HeaderFrom               = "From"
	HeaderHost               = "Host"

	HeaderIfMatch            = "If-Match"
	HeaderIfModifiedSince    = "If-Modified-Since"
	HeaderIfNoneMatch        = "If-None-Match"
	HeaderIfRange            = "If-Range"
	HeaderIfUnmodifiedSince  = "If-Unmodified-Since"
	HeaderLastModified       = "Last-Modified"
	HeaderLink               = "Link"
	HeaderLocation           = "Location"
	HeaderMaxForwards        = "Max-Forwards"
	HeaderOrigin             = "Origin"
	HeaderPragma             = "Pragma"
	HeaderProxyAuthenticate  = "Proxy-Authenticate"
	HeaderProxyAuthorization = "Proxy-Authorization"
	HeaderRange              = "Range"
	HeaderReferer            = "Referer"
	HeaderRetryAfter         = "Retry-After"
	HeaderServer             = "Server"
	HeaderSetCookie          = "Set-Cookie"
	HeaderSetCookie2         = "Set-Cookie2"
	HeaderTE                 = "TE"
	HeaderTrailer            = "Trailer"
	HeaderTransferEncoding   = "TransferEncoding"
	HeaderUpgrade            = "Upgrade"
	HeaderUserAgent          = "UserAgent"
	HeaderVary               = "Vary"
	HeaderVia                = "Via"
	HeaderWarning            = "Warning"
	HeaderWWWAuthenticate    = "WWW-Authenticate"
)
